name: merge
run-name: ${{ github.actor }} is merging
on:
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0

      - name: Install depependencies
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false