name: merge
run-name: ${{ github.actor }} is merging
on:
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install depependencies
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .docker/Dockerfile.deps
          push: false
          tags: deps
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar

  copy-code:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Load Docker image
        run: |
          docker load --input /tmp/image.tar
          docker image ls -a

      - name: Set environment variables
        run: |
          export DOCKER_BUILDKIT=0
          export COMPOSE_DOCKER_CLI_BUILD=0

      - name: Copy code
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/Dockerfile.copy
          push: false
          load: true
          network: none
          tags: copy

      - name: Export image
        run: docker save copy > /tmp/copy.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: copy
          path: /tmp/copy.tar

  lint:
    needs: copy-code
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: copy
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/copy.tar
          docker image ls -a

      - name: Lint
        run: docker run copy:latest npm run lint